const datalist =  [
    {
      name: '张三',
      place: '管理员',
      occupation: '洗手剂',
      phoneNumber: '2020-11-23',
      sex:  12,
      age: '张三',
    },
    {
      name: '李四',
      place: '职工',
      occupation: '毛巾',
      phoneNumber: '2020-11-23',
      sex: 21,
      age: '李四',
    },
    {
      name: '李超',
      place: '管理员',
      occupation: '厕纸',
      phoneNumber: '2020-4-3',
      sex: 12,
      age: '李四',
    },
    {
      name: '阿斯顿',
      place: '职工',
      occupation: '清洁剂',
      phoneNumber: '2020-8-4',
      sex: 34,
      age: '李四',
    },
    {
      name: '王武',
      place: '职工',
      occupation: '脚垫',
      phoneNumber: '2020-3-4',
      sex: 34,
      age: '王武',
    },
    {
      name: '十大',
      place: '职工',
      occupation: '厕纸',
      phoneNumber: '2020-3-4',
      sex: 13,
      age: '王武',
    },
    {
      name: '六十',
      place: '职工',
      occupation: '洗手剂',
      phoneNumber: '2020-4-5',
      sex: 4,
      age: '王武',
    },
    {
      name: '六朝',
      place: '职工',
      occupation: '洗手液',
      phoneNumber: '2020-4-6', 
      age: '李四',
      sex: 1,
    },
  ]
export default datalist